### ISSUE TITLE
0.1 Initial release todo list

### ISSUE THREAD

**Issue by sasdf** [sasdf/firstblood#1]
## general
- [x] pip package

## document
- [ ] Setup sphinx

## test
- [x] uio.file
- [ ] uio.sock
- [x] uio.spawn
- [ ] uio.buffer unit test
- [ ] uio.interact

## uio
- [x] uio.open and uio.tcp
- [ ] uio.udp
- [ ] uio.bind
- [x] uio.stdio
- [ ] threaded server of bind socket
- [x] uio.spawn
- [ ] uio.elf and uio.libc (pyelftool)
- [ ] uio.pe (pefile)
- [x] uio.UnifiedBase.timeout (timeout context manager)
- [x] Text IO in uio
- [x] remove redundant size arguments
- [x] uio.UnifiedBase.readsome
- [x] abstraction on output function
- [ ] uio.UnifiedBase.regex
- [ ] tell method
- [x] uio.UnifiedBase.interact
- [x] escape sequence input in uio.UnifiedBase.interact
- [x] seperate interact stdio to UnifiedInteract and InteractIOBuffer
- [x] refactor UnifiedFile and UnifiedFileDuplex to mixins
- [x] change UnifiedBase to mixin
- [x] handle non-str and bytes
- [ ] overflow check in uio.buffer.*

## patches
- [ ] str method of file operation
- [ ] function compose
- [ ] refactor to a structure which can insert docstring

## modulo and math
- [ ] wrap sympy and libnum in modulo
- [ ] matrix operations

## utils
- [ ] utils.disasm (capstone)
- [x] utils.asm (keystone)
